optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 2e-4
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 1
  verbose: true
experiment_config:
  _target_: src.config.ExperimentConfig
  model_config:
    _target_: src.config.ModelConfig
    model: resnet18
    optimizer_frequency: 3
    interval: epoch
    monitor: mean_valid_loss
  data_config:
    _target_: src.config.DataConfig
    dataset_name: image_classification_dataset
    img_size:
    - 224
    - 224
    batch_size: 128
    data_split:
    - 0.8
    - 0.2
    num_workers: 4
    pin_memory: true
    persistent_workers: true
  trainer_config:
    _target_: src.config.TrainerConfig
    min_epochs: 5
    max_epochs: 54
    check_val_every_n_epoch: 3
    log_every_n_steps: 1
    gradient_clip_val: null
    gradient_clip_algorithm: null
    deterministic: false
    fast_dev_run: false
    default_root_dir: null
    detect_anomaly: false
    accelerator: auto
  project_config:
    _target_: src.config.ProjectConfig
    project_name: image_classification
    experiment_name: image_classification
    track_in_clearml: true
